censor_settings:
  enabled_parts:
  - "FEMALE_BREAST_EXPOSED"
  - "FEMALE_BREAST_COVERED"
  - "BUTTOCKS_EXPOSED"
  - "BUTTOCKS_COVERED"
  - "ANUS_EXPOSED"
  - "ANUS_COVERED"
  - "FEMALE_GENITALIA_EXPOSED"
  - "FEMALE_GENITALIA_COVERED"

  merge_settings:
    merge_groups:
    - [ "FEMALE_BREAST_EXPOSED", "FEMALE_BREAST_COVERED" ]

  default_part_settings:
    censors:
    - function: "box"
      args:
        colour: "BLACK"
    shape: "joint_ellipse"
