# Config details
file_prefix: ""
file_suffix: ""

uncensored_folder: "00_uncensored"
censored_folder: "01_censored"

debug_mode: False

# Parts Enabled
parts_enabled:
# Female
- "FACE_FEMALE"

- "ARMPITS_EXPOSED"
- "ARMPITS_COVERED"

- "FEMALE_BREAST_EXPOSED"
- "FEMALE_BREAST_COVERED"

- "BELLY_EXPOSED"
- "BELLY_COVERED"

- "BUTTOCKS_EXPOSED"
- "BUTTOCKS_COVERED"

- "ANUS_EXPOSED"
- "ANUS_COVERED"

- "FEMALE_GENITALIA_EXPOSED"
- "FEMALE_GENITALIA_COVERED"

- "FEET_EXPOSED"
- "FEET_COVERED"

# Male
# - "FACE_MALE"
- "MALE_GENITALIA_EXPOSED"
# - "MALE_BREAST_EXPOSED"


# Information on Merging Parts
merging:
  range: -1
  merge_groups:
  - [ "FEMALE_BREAST_EXPOSED", "FEMALE_BREAST_COVERED" ]

# Rendering Settings
rendering:
  smoothing: True

# Information
information:
  # Fall Back Options as "General" Settings
  defaults:
    censors: []

    state: "revealed"
    minimum_score: 0.20
    shape: "joint_box"

  FEMALE_BREAST_EXPOSED:
    state: "protected"
    censors:
    - function: "outline"
      args:
        colour: DARK_RED
    - function: "box"
      args:
        colour: "BLACK"
  FEMALE_BREAST_COVERED:
    state: "protected"
    censors:
    - function: "outline"
      args:
        colour: DARK_RED
    - function: "box"
      args:
        colour: "BLACK"

  FEMALE_GENITALIA_EXPOSED:
    state: "protected"
    margin: -0.3
    censors:
    - function: "outline"
      args:
        colour: DARK_RED
    - function: "box"
      args:
        colour: "BLACK"
  FEMALE_GENITALIA_COVERED:
    state: "protected"
    margin: -0.3
    censors:
    - function: "outline"
      args:
        colour: DARK_RED
    - function: "box"
      args:
        colour: "BLACK"

  BUTTOCKS_EXPOSED:
    state: "unprotected"
    censors:
    - function: "outline"
      args:
        colour: DARK_RED
    - function: "box"
      args:
        colour: "BLACK"
  BUTTOCKS_COVERED:
    state: "unprotected"
    censors:
    - function: "outline"
      args:
        colour: DARK_RED
    - function: "box"
      args:
        colour: "BLACK"

  ANUS_EXPOSED:
    margin: -0.2
  ANUS_COVERED:
    margin: -0.2

  BELLY_EXPOSED:
    margin: 0.4
  BELLY_COVERED:
    margin: 0.4

  FEET_EXPOSED:
    margin: 0.2
  FEET_COVERED:
    margin: 0.2
  FACE_FEMALE:
    margin: 0.2

  reverse_censors:
  - function: "outline"
    args:
      colour: DARK_RED
      thickness: 2
  - function: "greyscale"
    args:
      alpha: 0.8
  - function: "blur"
    args:
      factor: 8
