[tool.poetry]
name = "censorengine"
version = "0.2.0"
description = "This is an open censoring tool for NSFW images and videos"
authors = ["PartTimeDegen"]
license = "GPL"
packages = [
    { include = "censorengine", from = "src" },
]

[tool.poetry.dependencies]
python          = "^3.12"
PyYAML          = "^6"
numpy           = "^1"
opencv-python   = "^4"
pillow          = "^10"
pytest          = "^8"
nudenet         = "^3"
opencv-stubs    = "^0"
opencv-python-headless = "^4"
types-pyyaml = "^6.0.12.20240917"
pytest-timeout = "^2.3.1"
onnxruntime-gpu = "^1.19.2"
torch = "^2.5.0"

[tool.poetry.group.dev.dependencies]
snakeviz = "^2.2.2"
ruff            = "^0"
mypy            = "^1"
autoflake       = "^2"
pre-commit      = "^4"
pyclean         = "^3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
pythonpath = "src"