[project]
name = "censor-engine"
version = "0.1.0"
description = "Censor Engine, Censors 'stuff'"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastai>=2.1.10",
    "gdown>=5.2.0",
    "keras>=3.11.1",
    "mypy>=1.17.1",
    "nudenet>=3.4.2",
    "numpy>=2.3.2",
    "onnxruntime-gpu>=1.22.0",
    "opencv-python>=4.11.0.86",
    "opencv-python-headless>=4.11.0.86",
    "opencv-stubs>=0.1.0",
    "pillow>=11.3.0",
    "progressbar2>=4.5.0",
    "pydload>=1.0.9",
    "pyright>=1.1.403",
    "pytest>=8.4.1",
    "pyyaml>=6.0.2",
    "ruff>=0.12.7",
    "torch>=2.8.0",
    "types-pyyaml>=6.0.12.20250516",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
