# Config details
file_prefix: ""
file_suffix: ""

uncensored_folder: "00_uncensored"
censored_folder: "01_censored"

debug_mode: False

# Parts Enabled
parts_enabled:
# Female
- "FACE_FEMALE"

- "ARMPITS_EXPOSED"
- "ARMPITS_COVERED"

# - "FEMALE_BREAST_EXPOSED"
# - "FEMALE_BREAST_COVERED"

- "BELLY_EXPOSED"
- "BELLY_COVERED"

# - "BUTTOCKS_EXPOSED"
# - "BUTTOCKS_COVERED"

- "ANUS_EXPOSED"
- "ANUS_COVERED"

# - "FEMALE_GENITALIA_EXPOSED"
# - "FEMALE_GENITALIA_COVERED"

- "FEET_EXPOSED"
- "FEET_COVERED"


# Male
- "FACE_MALE"
- "MALE_GENITALIA_EXPOSED"
- "MALE_BREAST_EXPOSED"


# Information
information:
  # Rendering Settings
  smoothing: True

  # Information on Merging Parts
  merging:
    range: -1
    merge_groups:
    - ["FEMALE_BREAST_EXPOSED"]
    - ["FEMALE_BREAST_COVERED"]


  # Fall Back Options as "General" Settings
  defaults:
    minimum_score: 0.20
    censors: []
    shape: "bar"
    mergable: False
    margin: 0.0

  # Reverse Censor
  reverse_censor:
    enable: False
    censors:
    - function: "overlay"
      args:
        rgb_colour: "HOT_GREEN"
        alpha: 0.2

  FEMALE_BREAST_EXPOSED:
    margin: 0.3
    censors:
    - function: "outline"
      args:
        rgb_colour: "PINK"
    - function: "blur"
      args:
        factor: 20
    - function: "greyscale"
      args: {}

  FEMALE_GENITALIA_EXPOSED:
    margin: 0.3
    censors:
    - function: "outline"
      args:
        rgb_colour: "PINK"
    - function: "blur"
      args:
        factor: 20
    - function: "greyscale"
      args: {}
